import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithErrorHandling } from "../../app/api/baseApi";

// Weekly market reports, generated by the pipeline every Friday and served
// read-only (see /api/market-reports; /api/reports is the problem-report intake).
export type ReportSummary = {
    slug: string;
    title: string;
    publishedAt: string;   // yyyy-MM-dd
    summary: string;
}

export type MarketReport = ReportSummary & { bodyHtml: string };

export const reportsApi = createApi({
    reducerPath: 'marketReportsApi',
    baseQuery: baseQueryWithErrorHandling,
    endpoints: (builder) => ({
        fetchReports: builder.query<ReportSummary[], void>({
            query: () => 'market-reports',
        }),
        fetchReport: builder.query<MarketReport, string>({
            query: (slug) => `market-reports/${slug}`,
        }),
    }),
});

export const { useFetchReportsQuery, useFetchReportQuery } = reportsApi;
